[ADD] PROJECT MODEL
EntryDSM/Samoyed pull request #1
Opened 2020-07-01 10:33 UTC by Gaegul

서비스에 사용할 database model 생성

엔트리 전체 서비스 DATABASE MODEL을 코드상에서 정의 했습니다. 
DATABASE 모델과 맞지 않는 부분이나 오탈자 명세에 맞지 않는 부분에 대해서 자세하게 리뷰해 주세요.

2020-07-01 10:55 UTC, o-ozogie commented
엑셀 서비스와 관계 없는 Qna 모델이 정의 된 이유를 여쭤봐도 괜찮을까요?

2020-07-01 10:57 UTC, Gaegul commented
> 엑셀 서비스와 관계 없는 Qna 모델이 정의 된 이유를 여쭤봐도 괜찮을까요?

기본적으로 일단 다 정의해두었습니다. 로직상에서는 사용하지 않아도 혹시 모를 상황 대비, 및 추가 기능, 변동에 대한 대비로 생각하시면 될 것 같습니다.

2020-07-01 11:02 UTC, o-ozogie approved these changes

2020-07-02 01:55 UTC, LumpKim requested changes
nullable 필드 관련 수정이 필요해 보입니다. 기본키 설정이 되어 있지 않은 Column도 몇 군데 있으니 수정 부탁드립니다.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/admin.py
> +    name = Column(String(45), nullable=True)
DDL에서는 필드를 `NOT NULL`로 정의하고 있습니다. `nullable`을 false로 변경해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/calculated_score.py
> +    modified_at = Column(DATETIME, nullable=True)
DDL에서는 필드를 `NOT NULL`로 정의하고 있습니다. `nullable`을 false로 변경해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/calculated_score.py
> +    final_score = Column(DECIMAL(10, 5))
DDL에서는 필드를 `NULL`로 정의하고 있습니다. `nullable`을 true로 변경해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/ged_application.py
> +    ged_average_score = Column(Integer)
DDL에서는 필드를 `NULL`로 정의하고 있습니다. `nullable`을 true로 변경해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/ged_application.py
> +    modified_at = Column(DATETIME, nullable=True)
DDL에서는 필드를 `NOT NULL`로 정의하고 있습니다. `nullable`을 false로 변경해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/graduated_application.py
> +    student_number = Column(String(5))
DDL에서는 필드를 `NULL`로 정의하고 있습니다. `nullable`을 true로 변경해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/graduated_application.py
> +    school_tel = Column(String(20))
DDL에서는 필드를 `NULL`로 정의하고 있습니다. `nullable`을 true로 변경해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/graduated_application.py
> +    english = Column(String(6))
DDL에서는 필드를 `NULL`로 정의하고 있습니다. `nullable`을 true로 변경해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/graduated_application.py
> +    modified_at = Column(DATETIME, nullable=True)
DDL에서는 필드를 `NOT NULL`로 정의하고 있습니다. `nullable`을 false로 변경해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/qna.py
> +    is_read = Column(SMALLINT, nullable=True)
DDL에서는 필드를 `NOT NULL`로 정의하고 있습니다. `nullable`을 false로 변경해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/school.py
> +    school_address = Column(String(100), nullable=True)
DDL에서는 필드를 `NOT NULL`로 정의하고 있습니다. `nullable`을 false로 변경해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/qna.py
> +    qna_id = Column(Integer)
primary key 속성을 true로 설정해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/school.py
> +    school_code = Column(String(10))
primary key 속성을 true로 설정해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/school.py
> +    school_name = Column(String(45))
DDL에서는 필드를 `NULL`로 정의하고 있습니다. `nullable`을 true로 변경해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/status.py
> +    user_email = Column(ForeignKey("user.email"))
primary key 설정해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/status.py
> +    exam_code = Column(DATETIME)
DDL에서는 필드를 `NULL`로 정의하고 있습니다. `nullable`을 true로 변경해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/ungraduated_application.py
> +    user_email = Column(ForeignKey("user.email"))
primary key 설정해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/ungraduated_application.py
> +    student_number = Column(String(5))
DDL에서는 필드를 `NULL`로 정의하고 있습니다. `nullable`을 true로 변경해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/ungraduated_application.py
> +    english = Column(String(6))
DDL에서는 필드를 `NULL`로 정의하고 있습니다. `nullable`을 true로 변경해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/ungraduated_application.py
> +    modified_at = Column(DATETIME, nullable=True)
DDL에서는 필드를 `NOT NULL`로 정의하고 있습니다. `nullable`을 false로 변경해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/user.py
> +    email = Column(String(100))
primary key 설정해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/user.py
> +    receipt_code = Column(Integer, nullable=True)
DDL에서는 필드를 `NOT NULL`로 정의하고 있습니다. `nullable`을 false로 변경해주세요.

2020-07-02 01:55 UTC, LumpKim commented on samoyed/model/user.py
> +    study_plan = Column(String(1600))
DDL에서는 필드를 `NULL`로 정의하고 있습니다. `nullable`을 true로 변경해주세요.

2020-07-02 02:10 UTC, Gaegul commented
nullable 수정이 필요한 column은 전부 수정하였고, pk설정이 빠진 column도 확인해서 채워넣었습니다

2020-07-02 02:12 UTC, LumpKim requested changes
자료형이 DDL과 상이한 필드가 몇몇 있습니다. 추가로 수정 부탁드립니다.

2020-07-02 02:12 UTC, LumpKim commented on samoyed/model/status.py
> +    exam_code = Column(DATETIME)
exam_code 컬럼은 DATETIME이 아닌 VARCHAR(6)입니다.

2020-07-02 02:12 UTC, LumpKim commented on samoyed/model/user.py
> +    receipt_code = Column(Integer, nullable=True)
auto increment 설정해 주세요.

2020-07-02 02:25 UTC, LumpKim requested changes
school.school_code 기본키 설정해주세요.

2020-07-02 02:25 UTC, LumpKim commented on samoyed/model/school.py
> +    school_code = Column(String(10), nullable=True)
primary key 설정해주세욥

2020-07-02 02:30 UTC, LumpKim approved these changes
LGTM! 다음 PR 리뷰어로도 추가해주세요~

2020-07-02 02:31 UTC, merged