[ADD] Admission ticket api 개발
EntryDSM/Samoyed pull request #7
Opened 2020-08-13 01:06 UTC by Gaegul

# 수험표 출력 엑셀 api 개발
## 2차 면접 전 어드민에서 학생들 수험표를 출력하는 기능을 개발하였습니다.
### 요약
수험표 출력 기능 개발
## 영향을 미치는 부분
컨트롤러에 수험표 출력 로직이 추가되었습니다.

2020-08-13 01:33 UTC, LumpKim reviewed
먼저 [Samoyed#6](https://github.com/EntryDSM/Samoyed/pull/6)을 개선한 뒤 변경사항을 [Samoyed#7](https://github.com/EntryDSM/Samoyed/pull/7)에 병합해 주시기 바랍니다.

2020-08-19 09:58 UTC, LumpKim requested changes
1. samoyed/static/admission_ticket_2020-08-13-10:00:33.xlsx 지워주세요
2. 파일 이름에서 공백을 제거해주세요(samoyed/static/competition_status .xlsx)

2020-08-20 02:18 UTC, o-ozogie requested changes

2020-08-20 02:18 UTC, o-ozogie commented on samoyed/controller/admission_ticket.py
> +        for idx, user in enumerate(users):
(idx // 4 * 41)을 변수로 놓고 쓰면 가독성이 더 좋을 것 같습니다.

2020-08-30 14:07 UTC, closed without merging